% A generic test bench script without any Object Under Test.
% Generated by Audio Test Bench on 29-Oct-2019 16:16:18 +0000.

% Create test bench input and output
fileReader = dsp.AudioFileReader('Filename','meloyic.wav');
deviceWriter = audioDeviceWriter('SampleRate',fileReader.SampleRate);

scope = dsp.TimeScope('YLimits',[-1,1],'SampleRate',fileReader.SampleRate);

scope_spect = dsp.SpectrumAnalyzer('NumInputPorts',2,'SampleRate',fileReader.SampleRate);
%let us have an extra input to plot the before and after filtering

% [b,a] = butter(2,500/(fileReader.SampleRate/2)); 

% Stream processing loop

framesize = fileReader.SamplesPerFrame;

buffer_delay = 10*fileReader.SampleRate;
buffer = zeros(buffer_delay+framesize,2);

d1 = 0.1*fileReader.SampleRate;
g1 = 0.5;
d2 = 1*fileReader.SampleRate;
g2 = 0.3;
d3 = 4*fileReader.SampleRate;
g3 = 0.1;

while ~isDone(fileReader)
    % Read from input, process, and write to output
    in = fileReader();
    
    buffer(1:end-framesize,:) = buffer(framesize+1:end,:);
    buffer(end-framesize+1:end,:) = in;

    out = in + g1*buffer(buffer_delay-d1:buffer_delay-d1+framesize-1,:) + ...
                g2*buffer(buffer_delay-d2:buffer_delay-d2+framesize-1,:) + ...
                g3*buffer(buffer_delay-d3:buffer_delay-d3+framesize-1,:);  
            
            
g1 = (0.5)^3;        % specify gain of feedback and feedforward coefficients
g2 = (0.9)^5;
ff = [1 0 0 0 g1];      % Feedforward coefficients, M1=3
fb = [1 0 0 0 0 g2];  % Feedback coefficients, M2=5

y = filter(ff,fb,out);   % One-dimensional digital filter.
            
%      scope(out)
    scope(y)
    
%     deviceWriter(out);
deviceWriter(out)
end


% Clean up
release(fileReader)
release(deviceWriter)


